"""
Auto-generated deployed handler for resource: genothermal-fitness
Generated at: 2026-06-30T20:34:22.019042Z

Deployed endpoint handler: accepts plain JSON, no cloudpickle.
One function per endpoint, identified by FLASH_RESOURCE_NAME.

This file is generated by the Flash build process. Do not edit manually.
"""

import asyncio
import importlib
import inspect
import logging
import traceback

_logger = logging.getLogger(__name__)

# Import the function for this endpoint
score_endpoint = importlib.import_module('flash_fitness').score_endpoint


def handler(job):
    """Handler for deployed QB endpoint. Accepts plain JSON kwargs."""
    raw_input = job.get("input")
    if raw_input is None:
        raw_input = {}
    if not isinstance(raw_input, dict):
        return {"success": False, "error": f"Malformed input: expected dict, got {type(raw_input).__name__}"}
    raw_input.pop("__empty", None)
    job_input = raw_input
    try:
        result = score_endpoint(**job_input)
        if inspect.iscoroutine(result):
            try:
                loop = asyncio.get_running_loop()
            except RuntimeError:
                loop = None
            if loop and loop.is_running():
                import concurrent.futures

                with concurrent.futures.ThreadPoolExecutor() as pool:
                    result = pool.submit(asyncio.run, result).result()
            else:
                result = asyncio.run(result)
        return result
    except Exception as e:
        _logger.error(
            "Deployed handler error for score_endpoint: %s",
            e,
            exc_info=True,
        )
        return {"success": False, "error": str(e), "traceback": traceback.format_exc()}


if __name__ == "__main__":
    import runpod
    runpod.serverless.start({"handler": handler})
