"""Unified resource configuration for all resources.

THIS FILE IS AUTO-GENERATED BY FLASH BUILD - DO NOT EDIT

Generated configuration tells the @remote decorator which functions
should execute locally vs create stubs for remote calls, based on
the FLASH_RESOURCE_NAME environment variable.
"""

import os
from typing import Set

# Mapping of resource name to set of local function names
RESOURCE_LOCAL_FUNCTIONS = {
    "genothermal-fitness": {"score_endpoint"},
}

# Set of all known functions in the manifest
ALL_KNOWN_FUNCTIONS = {"score_endpoint"}


def is_local_function(func_name: str) -> bool:
    """Check if a function should execute locally in the current resource.

    Uses FLASH_RESOURCE_NAME environment variable to determine the current
    resource, then checks if the function belongs to that resource.

    Handles the -fb suffix that RunPod backend historically added to flashbooted endpoints.

    Args:
        func_name: Name of the function

    Returns:
        True if function should execute locally, False if it needs a stub
    """
    # Get current resource from environment
    current_resource = os.getenv("FLASH_RESOURCE_NAME")

    if not current_resource:
        # No resource name set - assume local for safety
        return True

    # Handle -fb suffix that RunPod backend historically added to flashbooted endpoints
    # Try exact match first, then with -fb suffix, then without -fb suffix
    local_functions = RESOURCE_LOCAL_FUNCTIONS.get(current_resource)
    if local_functions is None:
        local_functions = RESOURCE_LOCAL_FUNCTIONS.get(current_resource + "-fb")
    if local_functions is None:
        local_functions = RESOURCE_LOCAL_FUNCTIONS.get(current_resource.removesuffix("-fb"))

    if local_functions is None:
        local_functions = set()

    # Three cases:
    # 1. Function in local set -> execute locally (True)
    # 2. Function known but not in local set -> remote execution (False)
    # 3. Function completely unknown -> execute locally for safety (True)
    if func_name in local_functions:
        return True
    if func_name in ALL_KNOWN_FUNCTIONS:
        return False  # Known to exist in other resource
    return True  # Unknown function, default to local for safety
